name: deploy-website

on:
  push:
    paths-ignore:
      - '.git**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website
        uses: actions/checkout@master
        with:
          path: exult-web-master
      - name: Upload and update website
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          cd exult-web-master
          ./gen-snapshot-file-details.sh
          cd ..
          zip -9 master.zip -r exult-web-master
